### ISSUE TITLE
Error when using "l" and "p" argument together

### ISSUE THREAD

**Issue by zhouanbo** [kizz/nolu#1]
Hi, 

Liking this library a lot! I very glad I'm able to use javascript for shell scripting with this package.
The issue is, when I use `nolu -alpe '{a=$F[1]}' < aaa.txt`, the following error appears:
```
fs.js:763
  return binding.writeString(fd, buffer, offset, length, position);
                 ^

Error: EPIPE: broken pipe, write
    at Object.fs.writeSync (fs.js:763:18)
    at printNoNewline (/usr/local/lib/node_modules/nolu/lib/nolu.js:60:36)
    at printLine (/usr/local/lib/node_modules/nolu/lib/nolu.js:61:28)
    at executeAndPrint (/usr/local/lib/node_modules/nolu/lib/nolu.js:71:31)
    at codes.forEach (/usr/local/lib/node_modules/nolu/lib/nolu.js:119:33)
    at Array.forEach (<anonymous>)
    at lines.forEach (/usr/local/lib/node_modules/nolu/lib/nolu.js:119:15)
    at Array.forEach (<anonymous>)
    at ReadStream.inStream.on (/usr/local/lib/node_modules/nolu/lib/nolu.js:113:13)
    at ReadStream.emit (events.js:180:13)
```

Could you look into it and see what wrong?

Thanks!

**Comment by kizz** [comment]
Thanks to report a problem!
I tried to run the same command on my machine (mac) but got no errors...:

```
$ node -v
v7.7.2
$ nolu -v
0.0.3
$ cat aaa.txt 
Foo
Bar
Zoo
$ nolu -alpe '{a=$F[1]}' < aaa.txt
Foo
Bar
Zoo
```

Hmm... it may be a platform-specific problem. Could you tell me your environment? (i.e. OS and its version, Node.js version)

**Comment by zhouanbo** [comment]
Hi,
I when back and looked at my history, it's actually all good! It's because I tested on a large file and I piped the result to "head" so it breaks the output stream. The error message should be an expected behavior. Sorry for the trouble...
BTW, I briefly look at the source code and find out the way nolu deal with multi line file is to read them all at once and them split. Are you interested to modify it to use the "readline" module from nodejs?
Thanks for your prompt response!

**Comment by kizz** [comment]
Oh, glad to hear the problem is solved.

> Are you interested to modify it to use the "readline" module from nodejs?

Well, I haven't known the module.

Actually the current implementation does not read a whole file at once for `-n` or `-p` options (though I haven't tried very large files...). Each time a chunk of the file is read, it should be splitted and processed.  (Since nolu listens the `"data"` event of the `ReadableStream` for the file. [nolu.js#L107](https://github.com/kizz/nolu/blob/b5925e283116b11a6a1cdcfb301470dcc9aa67c3/lib/nolu.js#L107))

I checked the source code of the "readline" module and found that it is a kind of a wrapper of `ReadableStream`. It also [listens `"data"` event](https://github.com/nodejs/node/blob/master/lib/readline.js#L184). So it seems that they are essentially same, no performance advantage for handling large files.

Anyhow, thanks for your advice!
Please don't hesitate to let me know If you have any performance trouble with large files. (unless using `-t` or `-j`, they require a whole file at once!)
